var colors = {
  background: {
    default: "#FFFFFF",
    "default-gradient": "#FFFFFF",
    paper: "#EEEEEE",
  },
  primary: {
    empty: "#FFFFFF",
    "empty-focus": "#e8e8e8",
    "empty-active": "#dbdbdb",
    "empty-text": "#000000",
    subtle: "#D6F2FF",
    "subtle-focus": "#bdeaff",
    "subtle-active": "#a3e2ff",
    "subtle-text": "#000000",
    main: "#47C5FC",
    "main-focus": "#5ecdfd",
    "main-active": "#77d6fe",
    "main-text": "#FFFFFF",
  },
  secondary: {
    main: "",
  },
  neutral: {
    empty: "#F5F5F5",
    "empty-focus": "#e8e8e8",
    "empty-active": "#dbdbdb",
    "empty-text": "#000000",
    subtle: "#D6F2FF",
    "subtle-focus": "#bdeaff",
    "subtle-active": "#a3e2ff",
    "subtle-text": "#000000",
    main: "#AAAAAA",
    "main-focus": "#888888",
    "main-active": "#000000",
    "main-text": "#FFFFFFF",
  },
  error: {
    empty: "#F5F5F5",
    "empty-focus": "#F5F1F1",
    "empty-active": "#F5F1F1",
    "empty-text": "#FF0000",
    subtle: "#FF0000",
    "subtle-focus": "#FF0000",
    "subtle-active": "#FF0000",
    "subtle-text": "#FFFFFF",
    main: "#FF0000",
    "main-focus": "#FF0000",
    "main-active": "#FF0000",
    "main-text": "#FFFFFF",
  },
  warning: {
    main: "",
  },
  success: {
    main: "",
  },
};

module.exports = colors;
